### PR TITLE
Normalize all the line endings

### PR DESCRIPTION
**Pull request by jojorne**
Ok... So all the sudden my repo was giving me "all the files are modified" with no diff at all.
It turns out that after you add ".gitattributes" you need to normalize all the line endings...

https://help.github.com/articles/dealing-with-line-endings/

Also ".gitignore" is really outdated. So I took the liberty to update it with Visual Studio's default one and it works! The "obj" folder is not included anymore nor the ".vs" folder.

PS.: "lsl-editor-doc.xml" is on ".gitignore" but also included inside the repo, why? Should I remove it from the the repo or the ".gitignore"?

### CODE REVIEW

**Comment by jojorne** [comment]
Ah! And this "**All checks have failed**" error is because you switched to ".Net Core" instead of "Mono".

**Comment by niel** [comment]
You're partially correct.
You are not so much normalising the line endings as doing a reset on the files to adopt the new state inside the repository. The end result is much the same though, from your point of view.

That "All checks have failed" isn't because of the ".Net Core" Inside the yaml, it's because the checks failed :-) They fail whether it's set to MOono or .NET Core, because the test environment doesn't have some of the dependencies (none of the Windows specific stuff mostly). Unfortunately, the only around that is to remove the dependencies (or turn off the checking entirely). This is what I said previously about having to get the CI working. I think for the short term I'm going to give up on that and just disable Travis. I've been looking around for alternatives, but can't find anything that doesn't either require a Windows server, or have recurring fees.

**Comment by niel** [comment]
Looking into the line endings :-( I may have been on Linux for too long and forgotten the hassles of dealing with Windows :-)

**Comment by jojorne** [comment]
Uh... Testing here:
- dotnet build: I got same error on my end (error MSB3644).
.Net 3.5 is not supported by Microsoft.
- Switching the project to .Net .4.5 and...
warning CS0168: "e" never used on "trunk\lsleditor.csproj".
CSC : error CS1508: Identifier already used "Resources.resx" and "Unknown.gif" on "trunk\lsleditor.csproj".

**Comment by niel** [comment]
Those .gitignore additions look excessive. Can't you just ignore the entire directory tree where the building is done, instead of specifying every file type that might occur?

**Comment by jojorne** [comment]
Uh, I could try to remove some but I don't know exactly which one. You could change it after the merge tho.
But I m curiouse about the "dotnet build" on ".Net 4.5", it works!

**Comment by niel** [comment]
Can't find a way to PM. So here https://discord.gg/eXFUyq ;-)

**Pull request merged**
